language: python
python:
  - "2.7"

addons:
  apt:
    packages:
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - libffi-dev
    - libyaml-dev
    - libssl-dev

install: "pip install -r requirements-dev.txt"

script: nosetests

sudo: false
